### ISSUE TITLE
Kilka zbędnych regułek

### ISSUE THREAD

**Issue by ghost** [adblockpolska/Adblock_PL_List#6]
Właśnie znalazłem ciekawe [narzędzie](https://arestwo.org/famlam/redundantRuleChecker.html) do sprawdzania subskrypcji ABP. Pokazuje mi kilka zbędnych reguł:

```
##.forceRefresh.disableScreeningClick.adoHide.adoSlv.OnTop has been made redundant by ##.adoHide.adoSlv.OnTop
tvn24.pl##[class^="adoHide"] has been made redundant by ##[class^="adoHide"]
fukk.pl###comment-captcha has been made redundant by pl###comment-captcha
optyczne.pl##.skyscraper has been made redundant by pl##.skyscraper
||myao.adocean.pl$domain=tvp.pl has been made redundant by ||adocean.pl
||tvn.adocean.pl/files/*.swf has been made redundant by ||adocean.pl
||gg.adocean.pl$third-party has been made redundant by ||adocean.pl
```

**Comment by adblockpolska** [comment]
Racja, racja, dawno nie skanowałem tym wihajstrem :) Dzięki za czujność!

**Comment by ghost** [comment]
@adblockpolska rzucil byś jeszcze okiem na zakładkę `warnings (0+10)`. Pokazuje tam kilka miejsc, gdzie można by usunąć lub dodać `*`.

**Comment by adblockpolska** [comment]
No z tymi warningami nie zawsze radzi dobrze, ale część faktycznie można
poprawić. Lista polska będzie przechodziła gruntowny remanent przy
wcielaniu na serwery EasyList :)

W dniu 30 września 2014 10:36 użytkownik gwarser notifications@github.com
napisał:
