### ISSUE TITLE
pclab.pl

### ISSUE THREAD

**Issue by ghost** [adblockpolska/Adblock_PL_List#8]
Można oprócz tych obrazków po bokach wywalić również linki? Może: `#spon_left` i `#spon_right`? 

Cały czas tam klikam środkowym klawiszem, jak chcę autoscrolla włączyć.

Przykład http://pclab.pl/news60530.html

**Comment by adblockpolska** [comment]
Hmmm, dziwne, ale u mnie nie ma żadnych linków... może to była jakaś czasowa reklama?

**Comment by ghost** [comment]
Pewnie tak.

**Comment by ghost** [comment]
@adblockpolska commented on [15 lis 2014, 00:57 CET](https://github.com/adblockpolska/Adblock_PL_List/issues/8#issuecomment-63148166):

> Hmmm, dziwne, ale u mnie nie ma żadnych linków... może to była jakaś czasowa reklama?

Znowu to włączyli. Myślisz, że warto to blokować, czy mam zamknąć zgłoszenie?
//
Nie, sorry - wyłączyłem filtrowanie.
