### ISSUE TITLE
Zbyt dużo wyjątków?

### ISSUE THREAD

**Issue by ghost** [adblockpolska/Adblock_PL_List#9]
W repo µBlocka @konto-andrzeja [zauważył](https://github.com/gorhill/uBlock/issues/915#issuecomment-76662415), że w liście jest chyba zbyt dużo wyjątków. Mógłbyś się do tego odnieść?
I co z tymi przenosinami na serwery EasyList, bo ostatnio coś mało aktualizacji.

W międzyczasie znalazłem też inną listę od [certyficate.it](http://certyficate.it/polski-filtr-adblock/). Niby jest aktualizowana, ale filtry w niej to jakiś kompletny bajzel i chyba powoduje jeszcze [większe problemy](https://github.com/gorhill/uBlock/issues/917#issuecomment-76926840)

**Comment by MajkiIT** [comment]
Ja używam i nie ma żadnego bajzlu.

**Comment by ghost** [comment]
@marek45 commented on [9 mar 2015, 18:49 CET](https://github.com/adblockpolska/Adblock_PL_List/issues/9#issuecomment-77905374):

> Ja używam i nie ma żadnego bajzlu.

;)

Po pierwsze, to była cała masa duplikatów, i dopiero jak [napisałem komentarz by użyli redundantRuleChecker](http://certyficate.it/polski-filtr-adblock/#comment-8385) to je wyczyszczono.
Po drugie jest cała masa niezupełnie poprawnych filtrów zaczynających lub kończących się gwiazdką (`*`) - jak ostatnio patrzyłem, to Adblock Plus krzyczał. że takie filtry są wolne przy parsowaniu.
Po trzecie zupełnie niepotrzebne duplikowanie filtrów które mógłby załatwić jeden, jak np.

```
##*#dynAdv57
##*#dynAdv56
##*#dynAdv55
##*#dynAdv54
...
```

(no i po co ta gwiazdka na początku?)
No i tak w ogóle to mogli by tą listę trochę posortować, bo aż oczy bolą jak ją przeglądam.

**Comment by MajkiIT** [comment]
Jak napisałeś to chwała Ci za to. Wszystkim powinno zależeć na rozwoju tego. Dostajesz coś za freeko coś co działa, lecz ma wady i "marudzisz" . Nie dziwię się, że lista adblock Polska przestała być aktualizowana, bo pewnie tylko słyszeli tylko takie podejście a nie wsparcie. Ktoś podjął się roboty hobbistycznie to doceń to a nie szukasz dziury w całym. Ja tam jestem zadowolony, bo podziwiam, że komuś się chce.
